### ISSUE TITLE
Updating from 3.10 to 3.12 causes crash: 

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1179]
I just updated to 3.12 and now my charts are crashing with "cannot read property 'logarithmic' of undefined'

It seems it's a problem in setYScaleForIndex in Scales.js. CoreUtils also looks for a 'logarithmic' property, but it couldn't be causing the crash because it makes sure the object it's checking the property on is defined. In this case, it appears the `y` is undefined.

I'm unsure why this crash would occur after the update, but never happened before. Nothing in my code has changed.

**Comment by junedchhipa** [comment]
Can I get a codepen example, please?

**Comment by ThinkSalat** [comment]
I can try! Could this be related to these breaking changes?

- Unused SVG.js code removed to bring down bundle size. Minified 449kB reduced to 425kB.
- Removed IE11 polyfills and added lists of polyfills to add for IE11 support.
- In radar chart, renamed the outer data labels as xaxis labels.

It's weird. I updated, it started crashing. I reverted to 3.10 and it stopped crashing.

The only place where this could be happening is in Scales.js. I looked through the changes for that file and didn't find anything could have caused it, but noticed the `y` which is undefined in this instance is coming from cnd.yaxis[index] (I'm not using a horizontal bar)

has there been a change in the way the index is passed to the `setYScaleForIndex` function? Has there been a change in the config.yaxis?

**Comment by junedchhipa** [comment]
No, there was no major change to the scaling code, so I doubt that is the issue.
A codepen will definitely help!

**Comment by ThinkSalat** [comment]
I can't seem to replicate it. And for some reason, it's now working just fine. Thanks for the help!

**Comment by ThinkSalat** [comment]
It's really random. I closed this issue twice because I thought I had solved it but then it comes back. I'm not sure how to produce a codepen for it because it happens so randomly

**Comment by ThinkSalat** [comment]
Here is the error:

apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read property 'logarithmic' of undefined
    at t.value (apexcharts.common.js:6)
    at t.value (apexcharts.common.js:6)
    at t.value (apexcharts.common.js:6)
    at t.value (apexcharts.common.js:6)
    at t.value (apexcharts.common.js:14)
    at t.create (apexcharts.common.js:6)
    at apexcharts.common.js:14
    at new Promise (<anonymous>)
    at t.value (apexcharts.common.js:14)
    at r.value (react-apexcharts.min.js:1)
    at commitLifeCycles (react-dom.development.js:22068)
    at commitLayoutEffects (react-dom.development.js:25302)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at commitRootImpl (react-dom.development.js:25040)
    at unstable_runWithPriority (scheduler.development.js:818)
    at runWithPriority$2 (react-dom.development.js:12130)
    at commitRoot (react-dom.development.js:24889)
    at finishSyncRender (react-dom.development.js:24296)
    at performSyncWorkOnRoot (react-dom.development.js:24274)
    at react-dom.development.js:12180
    at unstable_runWithPriority (scheduler.development.js:818)
    at runWithPriority$2 (react-dom.development.js:12130)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12175)
    at flushSyncCallbackQueue (react-dom.development.js:12163)
    at batchedUpdates$1 (react-dom.development.js:24359)
    at Object.notify (Subscription.js:23)
    at Subscription.notifyNestedSubs (Subscription.js:65)
    at Subscription.handleChangeWrapper (Subscription.js:70)
    at Object.dispatch (redux.js:221)
    at e (<anonymous>:1:40553)
    at middleware.js:22
    at middleware.js:66
    at dispatch (redux.js:636)
    at utils.js:250
    at proc.js:489
    at exec (scheduler.js:19)
    at flush (scheduler.js:60)
    at asap (scheduler.js:33)
    at runPutEffect (proc.js:486)
    at runEffect (proc.js:435)
    at next (proc.js:315)
    at currCb (proc.js:388)

**Comment by ThinkSalat** [comment]
Here's the options  I'm using - mind the colors: [null] thing is because i'm using a function to decide which color the series is, and I think the JSON.stringify deletes functions.

The series is an empty array.

```
{
	"chart": {
		"fontFamily": "Quicksand, Times New Roman, Times, serif, sans-serif",
		"toolbar": {
			"show": false
		},
		"zoom": {
			"enabled": false
		},
		"fontSize": "15px",
		"animations": {
			"enabled": false
		},
		"parentHeightOffset": -150,
		"id": "29d6a9c9c41aa96ad1d852eab6979ba7_1",
		"events": {}
	},
	"grid": {
		"xaxis": {
			"lines": {
				"show": false
			}
		},
		"yaxis": {
			"lines": {
				"show": false
			}
		}
	},
	"dataLabels": {
		"enabled": false
	},
	"selection": {
		"enabled": false
	},
	"tooltip": {
		"enabled": true,
		"shared": true,
		"followCursor": false,
		"fixed": {
			"enabled": false,
			"position": "top"
		}
	},
	"xaxis": {
		"type": "datetime",
		"tooltip": {
			"enabled": false
		},
		"max": 1578095908668,
		"crosshairs": {
			"show": true
		},
		"min": 1575590310363,
		"tickPlacement": "on"
	},
	"legend": {
		"show": false
	},
	"noData": {
		"offsetX": -30,
		"text": "No tracking reported for this period",
		"style": {
			"color": "darkgrey",
			"fontSize": "20px",
			"fontFamily": "Quicksand"
		}
	},
	"markers": {
		"size": [],
		"discrete": [],
		"colors": []
	},
	"stroke": {
		"width": [],
		"dashArray": []
	},
	"colors": [null],
	"yaxis": [],
	"annotations": {
		"xaxis": []
	}
}


```

**Comment by ThinkSalat** [comment]
OH now I see it. the empty array in yaxis was causing a crash. Maybe you can make a warning message, otherwise people may run into crashes like this.

**Comment by ThinkSalat** [comment]
In Scale.js it was attempting to access [][index].logarithmic which threw the error.

**Comment by junedchhipa** [comment]
Thanks for the catch!
Fixed it.

**Comment by juliorosseti** [comment]
I'm having the same problem, but I also can't simulate in codepen... 😥 (the solution did not solve for me)

**Comment by juliorosseti** [comment]
I could simulate my problem in codepen, you can take a look? @junedchhip

https://codepen.io/juliorosseti/pen/MWYzzPB?editors=1010

**Comment by juliorosseti** [comment]
I got a good result so that the error does not appear on the console: `Uncaught (in promise) TypeError: Cannot read property 'logarithmic' of undefined`.

It's necessary to leave a series preset with the key `data` being an empty array.

Before: https://codepen.io/juliorosseti/pen/MWYzzPB?editors=1010
```javascript 
series: []
```

After: https://codepen.io/juliorosseti/pen/YzPdywb?editors=1010
```javascript 
series: [
    {
         data: []
    }
]
```
