### ISSUE TITLE
Tooltip formatter in timeline charts

### ISSUE THREAD

**Issue by Hurenka** [apexcharts/apexcharts.js#1235]
https://codepen.io/catherin-waverly/pen/MWYzVMZ

- What is the behavior you expect?
I've expected that there'll be no seriesName before the colon inside the tooltip.
- What is happening instead?
I don't see that tooltip yaxis title formatter works.
- What error message are you getting?
No errors.

**Comment by junedchhipa** [comment]
Thanks for reporting the bug, I confirm the issue.
It will be addressed soon.

**Comment by junedchhipa** [comment]
Fixed it, will be working in the next release.

You will need to format the `tooltip.y.formatter` function.

```javascript
tooltip: {
  y: {
    formatter: function(val) {
       return 'val --'
    }
  }
}
```

**Comment by Hurenka** [comment]
Thanks, I'll be waiting

**Comment by thellimist** [comment]
@junedchhipa the formatter is still broken

https://codepen.io/thellimist/pen/mdyYZMX?editors=1111

This should print the dataPointIndex, however, the `obj` is being undefined and resetting constantly while hovering.
