### ISSUE TITLE
Responsive options dropped when doing updateOptions via exec

### ISSUE THREAD

**Issue by mestaritonttu** [apexcharts/apexcharts.js#154]
## Codepen

https://codepen.io/anon/pen/OBpYXW

## Explanation

Pen is a fork of the responsive example from ApexCharts docs.
Set your viewport size smaller than the breakpoint 1000.
Now select "2009" from the dropdown (it triggers the exec).
Notice the chart swings back to the wide screen options.

**Comment by junedchhipa** [comment]
This is very similar to #74. Thanks for the detailed explanation. 
Hopefully, will be fixed in the next release

**Comment by mestaritonttu** [comment]
Thanks for the quick fix! I tested the patch and confirm it is working. ApexCharts is looking pretty bad ass now.

**Comment by mestaritonttu** [comment]
I don't understand how it is possible, but it looks like the patch didn't work after all. If you open the Codepen example, go to Settings - JavaScript and change the url to https://cdn.jsdelivr.net/npm/apexcharts?v=214 (which should have the patch) or https://cdn.jsdelivr.net/npm/apexcharts?v=250 it makes no difference. The problem of the chart changing back to horizontal bars upon dropdown change remains.
I also confirm the problem with local .js files.

On 10 Oct, I manually applied the patch and tested and I have no idea why I now see different results.

**Comment by junedchhipa** [comment]
v2.1.6 broke the responsive options as there were some major changes.
Will be fixed soon

**Comment by junedchhipa** [comment]
Fixed in 2.5.1.
Please update using https://cdn.jsdelivr.net/npm/apexcharts@2.5.1

**Comment by mestaritonttu** [comment]
Thanks for the work, but I am still seeing the reset to horizontal both in the Codepen and locally when using 2.5.1

**Comment by junedchhipa** [comment]
I didn't update the codepen, but I see in your codepen you have appended `?v=251`
That is not the correct way to get the latest version.
Please use the following URL to get a specific version
https://cdn.jsdelivr.net/npm/apexcharts@2.5.1

Here is my codepen - https://codepen.io/apexcharts/pen/xmPJEL

**Comment by mestaritonttu** [comment]
Thanks, that codepen certainly confirms the fix! Yet, the dist/*.js files in the 2.5.1 release seem to contain the old version.
