### ISSUE TITLE
regression: chart.destroy() no longer works in 3.22.1

### ISSUE THREAD

**Issue by az143** [apexcharts/apexcharts.js#2020]
scenario: we have a set of synced time-series line charts, and some tickboxes de/selects one or more for subsequent re-charting. when a chart is deselected we call some_particular_chart.destroy() to get rid of it. 

with plain js apexcharts release 3.20 this works fine, but with release 3.22.1 the deselected chart remains on screen and some (all?) of its events remain active. there are no js console errors or warnings or exceptions.

the zombie chart is no longer synchronised with the others if i perform a selection zoom on one of the other charts, ditto pan on
one of the other charts; however, doing a selection zoom on the zombie chart does trigger updates on the other charts but NOT on the zombie itself.

**Comment by anncwb** [comment]
the same 
![image](https://user-images.githubusercontent.com/28132598/98076954-3bb62b00-1eaa-11eb-97cd-67c60e9d8d58.png)

**Comment by junedchhipa** [comment]
Can anyone of you provide a Codepen, please?

**Comment by FallDownTheSystem** [comment]
I can confirm that resize events are at least still triggering after destroy has been called. 3.22.0 works fine, 3.22.1 you get a lot of errors when resizing after calling .destroy().

**Comment by junedchhipa** [comment]
I have released 3.22.2
Please test and report if the new version fixes the issue.

**Comment by az143** [comment]
sorry, but 3.22.2 doesn't fix this: destroy() remains broken for synched charts. i don't have a codepen account, but it's easy to reproduce: i took your synced line chart demo from https://apexcharts.com/samples/vanilla-js/line/syncing-charts.html
and just added a button like this `<button onclick="chartLine2.destroy(); ">should remove line chart two</button>`.  click the button and the result is that line chart two remains on screen and is now behaving somewhat 
disconnected from the other two as i described in my original report. i've tested this in both firefox and chromium, same broken
behaviour.

see the attached html file: [reproduceme.zip](https://github.com/apexcharts/apexcharts.js/files/5507226/reproduceme.zip)

**Comment by junedchhipa** [comment]
@az143 Thanks for providing the step to reproduce.
Fixed it. Please wait for the next patch release.
