### ISSUE TITLE
[regression] v3.22.3 destroys the linegraph scaling, compared to v3.22.2

### ISSUE THREAD

**Issue by Knogobert** [apexcharts/apexcharts.js#2098]
# Bug report

## Codepen

https://codesandbox.io/s/vue-basic-example-forked-tt4ci?file=/src/components/Chart.component.vue

We're using vue-apexcharts and just updated the patch version from 3.22.2 to 3.22.3 and saw that it made our linegraphs unusable.

In codesandbox, change the version between 3.22.3 and 3.22.2 to see the issue. Example photos below

## Explanation

- What is the behavior you expect?
  - For the scale in apexcharts linegraph to work like it did in v3.22.2
- What is happening instead?
  - The linegraph gets cut off "softly", it doesn’t cut off the height "hard". So that's why I'm guessing it's the scaling that's off.
- What error message are you getting?
  - None

#### 3.22.3
<img width="1374" alt="apexcharts-bad-3 22 3" src="https://user-images.githubusercontent.com/770560/101643947-ef27b780-3a34-11eb-8474-05869ce1c66e.png">

#### 3.22.2
<img width="1374" alt="apexcharts-good-3 22 2" src="https://user-images.githubusercontent.com/770560/101643938-ec2cc700-3a34-11eb-8557-564247e4d5f9.png">

**Comment by jkohlin** [comment]
I've got the same issue.

**Comment by azivkovi** [comment]
Temporary fix is to remove `min` and `max ` definitions from y-axis options.

**Comment by junedchhipa** [comment]
Fixed it, a new version will be released very soon.

**Comment by cailloumajor** [comment]
I have the same problem, let's wait the fixing release 👀

**Comment by junedchhipa** [comment]
Released v3.23.0 which should fix this.

**Comment by Redirts** [comment]
Still not working I believe...

![image](https://user-images.githubusercontent.com/23477559/102226794-bd08d080-3ee0-11eb-8640-2562e82f8e3d.png)

**Comment by junedchhipa** [comment]
@Redirts Checked in the original Codesandbox of this issue by updating to the latest version and it works fine.
Can you provide another Codesandbox demo?

**Comment by Redirts** [comment]
> @Redirts Checked in the original Codesandbox of this issue by updating to the latest version and it works fine.
> Can you provide another Codesandbox demo?

Sorry, for some reason I cannot reproduce it anymore. My bad. Thanks
