### ISSUE TITLE
Chart breaking when zooming in and datalabels enabled

### ISSUE THREAD

**Issue by tommitchgl** [apexcharts/apexcharts.js#2807]
### Description

I have a series of bar charts that since the latest update (I think) break when using the zoom functionality ONLY when datalabels are turned on.

The console displays: 

**apexcharts:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'x')**

### Steps to Reproduce

1.  Set datalabels to enabled
2. Zoom into chart from default view

### Expected Behavior

If I zoom in on the chart, the chart should zoom in and not break.

### Actual Behavior

When I zoom in on the chart from the default view, the chart breaks and the above error is logged to the console.

Reproduction Link

https://codepen.io/tommitchy/pen/GRMRNZj

**Comment by praneetloke** [comment]
I am suspecting the changes from https://github.com/apexcharts/apexcharts.js/commit/e153a2bad82769197111b86fdc63ca6fe78fc33c is causing some issues with data labels. I am seeing some weird behavior too. I can confirm that using 3.30.0 I can zoom-in/out in that codepen (from this issue's description).

**Comment by junedchhipa** [comment]
As of 3.32.0, this issue has been fixed.

**Comment by randomnessdev** [comment]
Still happens to me in v3.45.2

<img width="534" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/35777896/ba837628-87dd-48d9-a463-aa55edaece6f">

**Comment by jscmidt** [comment]
I'm experiencing the same issue:
<img width="510" alt="Bildschirmfoto 2024-08-15 um 17 01 51" src="https://github.com/user-attachments/assets/0b531dd9-b586-4eaa-bf69-c625c44e5266">
