### ISSUE TITLE
apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'group')

### ISSUE THREAD

**Issue by sai12-creator** [apexcharts/apexcharts.js#4434]
apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'group')
    at apexcharts.common.js:6:166282
    at Array.forEach (<anonymous>)
    at apexcharts.common.js:6:166243
    at Array.forEach (<anonymous>)
    at t.value (apexcharts.common.js:6:166209)
    at t.value (apexcharts.common.js:6:172254)
    at t.value (apexcharts.common.js:6:168242)
    at t.value (apexcharts.common.js:6:417928)
    at t.value (apexcharts.common.js:14:37913)
    at t.create (apexcharts.common.js:6:4486)

**Comment by Nagu96** [comment]
I too faced the same issue. Its working fine in local, not working in dev portal.

**Comment by sai12-creator** [comment]
> I too faced the same issue. Its working fine in local, not working in dev portal. I am using "apexcharts": "3.35.3". May I know the version of yours?

Yes in local it's showing old  version and dev showing new  version so it's a bug in new version

**Comment by brianlagunas** [comment]
Did not follow bug template instructions. There is no actionable information in this bug report and the required repro app was not provided.

**Comment by sai12-creator** [comment]
> Did not follow bug template instructions. There is no actionable information in this bug report and the required repro app was not provided.

pls dont close apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'group')
at apexcharts.common.js:6:1
pls dont close this bug new version is giving this error if i pass single object in series like
series: [{name: 'values', data: [12,3,4,5,6,9]}]
and react version is 18.2 reactdom 18.2 react-apexchart: 1.4.1 apexchart: 3.49 npm: 9.5.7
if i pass multiple objects to series then chart is working only single line chart not coming due to single object.
series: [{name: 'values1', data: [12,3,4,5,6,9]}, {name: 'values2', data: [12,3,4,5,6,9]}, {name: 'values3', data: [12,3,4,5,6,9]}] its working

**Comment by sai12-creator** [comment]
> I too faced the same issue. Its working fine in local, not working in dev portal. I am using "apexcharts": "3.35.3". May I know the version of yours?

is it fixed? 6302578568

**Comment by Nagu96** [comment]
> 6302578568
Nope. Did u find the rootcause?

**Comment by sai12-creator** [comment]
> > 6302578568
> > Nope. Did u find the rootcause?

Yes bro cal me i will tell you fix

**Comment by Nagu96** [comment]
> > > 6302578568
> > > Nope. Did u find the rootcause?
> 
> Yes bro cal me i will tell you fix

Can you pls share me your mail id?

**Comment by sai12-creator** [comment]
> > > > 6302578568
> > > > Nope. Did u find the rootcause?
> > 
> > 
> > Yes bro cal me i will tell you fix
> 
> Can you pls share me your mail id?

Bro if single chart it's breaking with new version downgrade to 3.48 in package.json it will work

**Comment by Nagu96** [comment]
> > > > > 6302578568
> > > > > Nope. Did u find the rootcause?
> > > 
> > > 
> > > Yes bro cal me i will tell you fix
> > 
> > 
> > Can you pls share me your mail id?
> 
> Bro if single chart it's breaking with new version downgrade to 3.48 in package.json it will work

OK bro will check

**Comment by seniordev-ca** [comment]
Getting same error with 3.48 @sai12-creator

**Comment by sai12-creator** [comment]
Not sure it's fixed in 3.48 is it single chart issue in single line chart only  check package.json remove ^ symbol

**Comment by Nagu96** [comment]
> Not sure it's fixed in 3.48 is it single chart issue in single line chart only check package.json remove ^ symbol

Yes that is not fixed.I used apexcharts instead of ng-apexcharts
