### ISSUE TITLE
Missing first X-Axis label

### ISSUE THREAD

**Issue by MACscr** [apexcharts/apexcharts.js#475]
## Codepen

https://codepen.io/MACscr/pen/JVYvBN

## Explanation

Im not getting any errors, but cant figure out why my first date of March 26th isnt showing in the X axis. Data is plotted though.

I expect Mar 26 to show at the bottom just like the 27th is and every day after.

**Comment by junedchhipa** [comment]
Fixed in v3.12.0

**Comment by Khangng7** [comment]
I am using react-apexcharts@1.3.7 and apexcharts@3.18.1. This problem still exists.

**Comment by rajeshwarpatlolla** [comment]
I am using "apexcharts": "^3.17.0", still the problem exists.

**Comment by jaydublu2002** [comment]
All the working example conveniently have the 1st January as the first category - this is then displayed as "Jan '11" - I suspect the missing first label is caused if the 1st of the month is not one of the labels so it cannot put in year label anywhere ...

**Comment by joykliu** [comment]
Also happening to me still , apexcharts@3.19.3, react-apextcharts@1.3.7

<img width="1259" alt="Screen Shot 2020-07-28 at 8 34 59 AM" src="https://user-images.githubusercontent.com/7015521/88672608-42fcba00-d0ad-11ea-8c16-9c0248f534c5.png">

**Comment by joykliu** [comment]
Update ^^ 
I set an offset for the labels now the first label is showing up 

xaxis options: 

```
  xaxis: {
    type: "numeric",
    min: new Date("2020-07-07T00:00:00").getTime(),
    tickAmount: 13,
    labels: {
      formatter: (value: number) => moment(value).format("DD MMM"),
      offsetX: -35,
      offsetY: -10,
      style: {
        fontSize: "16px",
        colors: "#828282",
        fontFamily: "Calibri Regular",
        fontWeight: 400,
        cssClass: "apexcharts-xaxis-label"
      }
    },
    axisBorder: {
      show: false
    },
    axisTicks: {
      show: false
    }
  },
```

Rendering: 

<img width="1285" alt="Screen Shot 2020-07-28 at 8 43 19 AM" src="https://user-images.githubusercontent.com/7015521/88673727-93284c00-d0ae-11ea-89b0-b66b9494f7d7.png">

**Comment by rajeshwarpatlolla** [comment]
What if the label size is big. There has to be an option to automatically show the first label like every other graph libraries has.

**Comment by MichalWi** [comment]
FYI: Changing the formatter helped im my case

**Comment by Basir-PD** [comment]
Adding below `formatter` property in `labels` object of `xaxis` worked for me.

```
formatter: function(value, dateObj) {
  return moment(dateObj).format("ddd MM");
}
```
Weird! but worked for me.

**Comment by MichalWi** [comment]
This issue is not happening (in my case) when Y axis labels are present, so you can apply a very ugly workaround and define y axis labels but then add css class:
`yaxis.labels.cssClass: 'hidden'`.

`.hidden { display: hidden} `

**Comment by alec-irl** [comment]
Please reopen this issue. I am experiencing the same thing in the Year of Our Lord 2022

**Comment by GabyRibeiroCode** [comment]
I am facing the same problem, please could you reopen the issue. apexcharts 3.36.0 and ng-apexcharts 1.7.4.

**Comment by Mayank-jain34** [comment]
Hi Team, any update on this? I am also seeing this issue in the latest version.

**Comment by Joabesv** [comment]
Any news?
Having the same problem here with vue3-apexcharts

**Comment by yaminbyahiya** [comment]
Fixed the issue!

1. Change the type of xaxis to 'category'.
2. Add the following code to the labels of xaxis:                     
                        formatter: function(value, dateObj) {
                        const date = new Date(value);
                        const month = date.toLocaleString('default', { month: 'short' });
                        const day = date.getDate();
                        return `${day} ${month}`;
                    }
                    
                    
                    
The issue should be fixed by now!

**Comment by ShiftyMcCool** [comment]
@anirudhnykaa Thanks for the tip but, unfortunately, it's not working for me 😢

**Comment by GaborVxxx** [comment]
Hello PPL.
In my case. I explicitly set the categories:
        xaxis: {
            type: 'category',
            title: {
                text: paramsIn?.report_type
            },
            categories: dataIn ? dataIn.map(item => item.x) : [],  // Explicitly set categories
            labels: {
                rotate: -45,  // Add this line to rotate labels if they're overlapping
                formatter: function (value) {
                    return value ;  // Customize as needed
                }
            }
        }

+ Make sure the x: value is a string!!! On line below I just map over the data and cast it to string just to be sure.

const formatedData = data[0].data.map((item:{ x: string; y: number }) => ({ x: item.x.toString(), y: item.y / 100 })) // NEED to format label to string, or it will bug in some case...
