### ISSUE TITLE
Unnatural values on y axis

### ISSUE THREAD

**Issue by lukaszflorczak** [apexcharts/apexcharts.js#619]
## Codepen

<img width="1022" alt="Zrzut ekranu 2019-05-24 o 09 44 32" src="https://user-images.githubusercontent.com/1818979/58311135-94098200-7e08-11e9-88e2-e16156566c3f.png">

The red line uses the left yaxis, blues use the right one.

https://codepen.io/lukaszflorczak/pen/yrpWgZ?editors=1010

## Explanation

When I have a series where the only value is `1` and `0` and I also have `decimalsInFloat = true` (I have always integer values only) in yaxis option, the chart generates values: `0.2`, `0.4`, `0.6` etc. and rounds them to `0`, `0`, `0`, `1`, `1`, `1`. 

I expect that is should be only one `0` and one `1` or `0`, `1`, `2`, `3` etc. in this case.

**Comment by junedchhipa** [comment]
Thanks for the codepen demo.
Fixed the bug. Now the y-axis is not rounded when the numbers are too small. It will generate values like 0, 0.5, 1, 1.5...

**Comment by lukaszflorczak** [comment]
Hi. I checked version `3.7.0` but unfortunately, the problem still exists.

<img width="1434" alt="Zrzut ekranu 2019-05-28 o 06 41 27" src="https://user-images.githubusercontent.com/1818979/58451407-a8ed5a80-8113-11e9-8810-5e4c4cb7c72b.png">

https://codepen.io/lukaszflorczak/pen/yrpWgZ

* If I have only `0` values in series, the y axis looks proper: `0`, `1`, `2`, `3`, `4`, `5,
* If I have values lower than `5`, `decimalsInFloat: false` is ignored, and now in y axis I have float values with decimals

**Comment by lukaszflorczak** [comment]
Thank you for the update. Unfortunalety, I think it's still unnatural. Let's look at an example:

<img width="1432" alt="Zrzut ekranu 2019-05-30 o 09 50 11" src="https://user-images.githubusercontent.com/1818979/58617489-864c7480-82c0-11e9-9d34-39c6f4a46a85.png">

https://codepen.io/lukaszflorczak/pen/yrpWgZ?editors=1010

I have only integer values in series. And only `4` point in on the line, others are always somewhere between. Maybe in the y-axis (if there is `decimalsInFloat: false` option) should have values like `0`, `0.5`, `1`, `1.5` etc. if values in series are low? Or just `0`, `1`, `2`, `3` etc. like for only-zeros series?
