### ISSUE TITLE
Duplicated id:s when displaying more than one diagram on a page

### ISSUE THREAD

**Issue by kledung** [apexcharts/apexcharts.js#691]
Hi!
I´m displaying two pie diagrams on a page. When validating the content in Yellowlab.tools and Google Lighthouse (audit in Chrome DevTools)
there are erros due to duplicated id:s.

[id] attributes on the page are not unique
The value of an id attribute must be unique to prevent other instances from being overlooked by assistive technologies.

Failing Elements:
g#apexcharts-series-0.apexcharts-series.apexcharts-pie-series
path#apexcharts-donut-slice-0.apexcharts-pie-area
g#apexcharts-series-1.apexcharts-series.apexcharts-pie-series
path#apexcharts-donut-slice-1.apexcharts-pie-area
g#apexcharts-series-2.apexcharts-series.apexcharts-pie-series
path#apexcharts-donut-slice-2.apexcharts-pie-area
g#apexcharts-series-3.apexcharts-series.apexcharts-pie-series
path#apexcharts-donut-slice-3.apexcharts-pie-area

Is there way to solve this problem?
Best regards 
Kristian

**Comment by junedchhipa** [comment]
Thanks for reporting.
I have fixed it and the change will be reflected in the next version.

**Comment by marcamos** [comment]
Hello. Apologies for commenting in a closed issue, but I've just installed:

* `"apexcharts": "^3.40.0",`
* `"vue3-apexcharts": "^1.4.1",`

…and I'm still seeing duplicated IDs when there are more than one chart on a page:

<img width="1375" alt="Screenshot 2023-05-25 at 1 44 10 PM" src="https://github.com/apexcharts/apexcharts.js/assets/483840/c243019c-4395-4c76-af52-699b408630be">
