### ISSUE TITLE
'Symbol' is undefined on IE11 (type bar)

### ISSUE THREAD

**Issue by Micene09** [apexcharts/apexcharts.js#704]
#### Explanation
Chart displayed without any problem on init.
On mouseover a bar element, the error shows up.

#### Version
3.8.0

**Comment by junedchhipa** [comment]
I cannot reproduce the error.
Can you please post a codepen?

**Comment by Ox-Florian** [comment]
Hi,
The problem happens when you used the property
`tooltip : {
shared : true
}` in bar chart.
You used the JavaScript Object Symbol while it is not supported by IE 11

CodePen : https://codepen.io/ox-florian/pen/oNNByrg

**Comment by macoto-liu** [comment]
the same error, is there any workaround for this? 

the tooltip doesn't work while mouse over the chart on IE11.

**Comment by junedchhipa** [comment]
Fixed the issues and released new version 3.15.1. Please upgrade the library to the latest version

Add these IE11 polyfills in the header

```html
<script>
  window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"><\/script>');
  window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill@1.2.20171210/classList.min.js"><\/script>');
  window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/findindex_polyfill_mdn"><\/script>');
  window.Promise || document.write('<script src="https://cdn.jsdelivr.net/npm/blob-polyfill"><\/script>');		
</script>
```

It should work now.

**Comment by sreenukolla** [comment]
This is still an issue even hear 
https://apexcharts.com/javascript-chart-demos/heatmap-charts/basic/
when I open in IE11.
