### ISSUE TITLE
Annotation position still being calculated in pixels in version 3.8.0

### ISSUE THREAD

**Issue by ChrisMaunder** [apexcharts/apexcharts.js#743]
This is an further report of issue https://github.com/apexcharts/apexcharts.js/issues/627 

## Codepen

Version using Apexchartsjs 3.6.12: https://codepen.io/ChrisMaunder/pen/BgOYwq
Version using Apexchartsjs 3.8.0: https://codepen.io/ChrisMaunder/pen/EBeQvK

## Explanation

This seems to be the same issue as #627 except this affects "area" and "line" type charts.

**Comment by junedchhipa** [comment]
Thanks for reporting.
Fixed it.

**Comment by ChrisMaunder** [comment]
I'm still seeing exactly the same behaviour in my app and in the CodePen. I've updated the CodePen to v 3.81

**Comment by junedchhipa** [comment]
The bug fix will be released tomorrow in 3.8.2.
The above message was about the bug fix, not release :)

**Comment by ChrisMaunder** [comment]
Got it! I noticed the version was increased to 3.8.1 and thought, in my wild optimism assumed that was the fix. I appreciate the fast turn around, and also appreciate immensely the work you've put into this excellent control.
