### ISSUE TITLE
Datetime cut off for smaller width

### ISSUE THREAD

**Issue by silversillu** [apexcharts/apexcharts.js#799]
When the line chart has datetime on the X-axis and the chart width is quite small, the datetime labels are cut off on the right.

Also, if I have dates up to let's say 27th, I can sometimes see 28th, which can be quite confusing.

Example of the cut off datetime: https://i.imgur.com/qHcbn4z.png

**Comment by junedchhipa** [comment]
Which version of ApexCharts are you using?
As this bug was already fixed in the recent versions.

**Comment by silversillu** [comment]
I'm using `react-apexcharts`, updating to version 1.3.3 seems to have fixed it in some places, but not everywhere. See the screenshot: https://i.imgur.com/wnnj9pe.png

On another note, how to disable the beginning-of-the-month labels? `Jun '19` and `Jul '19` in my screenshot.´

Thanks

**Comment by silversillu** [comment]
Also this: https://i.imgur.com/kBvmPEc.png

The dataset is up to 1st of August and I can still see number 2 on the X axis.

**Comment by junedchhipa** [comment]
v3.11.3 fixes this behavior.
