### ISSUE TITLE
Wrong tick position and label when using datetime chart

### ISSUE THREAD

**Issue by astyfx** [apexcharts/apexcharts.js#822]
## Codepen
https://codepen.io/astyfx/pen/Vozymz

"apexcharts": "^3.8.3",
"react-apexcharts": "^1.3.3",

## Explanation
- What is the behavior you expect?
  - Correct position of tick and label
  - Display last tick's label when using datetime chart
- What is happening instead?
  - Wrong tick position
  - There is no last label
- What error message are you getting?
  - None

![Screen Shot 2019-08-02 at 1 58 49 PM](https://user-images.githubusercontent.com/4187285/62345760-71919480-b52e-11e9-9298-d3276a112613.png)

## Additional weird behavior on datetime chart (Month based)

![Screen Shot 2019-08-02 at 2 11 39 PM](https://user-images.githubusercontent.com/4187285/62346033-8e7a9780-b52f-11e9-8d24-c1aa64110851.png)
![Screen Shot 2019-08-02 at 2 11 45 PM](https://user-images.githubusercontent.com/4187285/62346036-8fabc480-b52f-11e9-994c-3d12bf1e0103.png)

I provide two serie [{x: '2019-07', y:0}, {x: '2019-08', y:0}]

and three more ticket label July 2019 showing could help on this also?

**Comment by junedchhipa** [comment]
Fixed in the latest version
![Screen Shot 2020-01-16 at 8 18 20 PM](https://user-images.githubusercontent.com/17950663/72534763-5d9fdc00-389d-11ea-9033-6229fe991635.png)

If you can reproduce the month based, please create a new ticket.

**Comment by davehowson** [comment]
This issue is still there in the Vue version of apexcharts. Appreciate if anyone could take a look at it.

![image](https://user-images.githubusercontent.com/26568721/99341832-a440d700-28b0-11eb-9510-883ab14581de.png)
